### PR TITLE
Attach sources and javadoc

### LINKED ISSUE #44: Deploy sources to repository
Can another jar be created which has the source code in it?
It would be good for IDE integration.

This can be done with the [maven-source-plugin](https://maven.apache.org/plugins/maven-source-plugin/)

### PR DESCRIPTION
**Pull request by timja-kainos**
This attaches sources and javadoc on deploy
Fixes #44 

See [stackoverflow](http://stackoverflow.com/a/37798726/4951015)

### CODE REVIEW

**Comment by quis** [comment]
test this please

**Comment by quis** [comment]
Previous comment directed @govuk-notify-jenkins !

**Comment by timja-kainos** [comment]
@quis Is it possible to get this merged?

**Comment by quis** [comment]
@servingUpAces Can you take a look at this please?

**Pull request merged**
